const TasksActionTypes = {
    GET_TASKS_START: "GET_TASKS_START",
    GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
    GET_TASKS_FAILURE: "GET_TASKS_FAILURE",
    ADD_TASK_START: "ADD_TASK_START",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
    UPDATE_TASK_START: "UPDATE_TASK_START",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
    DELETE_TASK_START: "DELETE_TASK_START",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE"
};

export default TasksActionTypes;